[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
via_ir = true

[rpc_endpoints]
base = "https://mainnet.base.org"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
optimism = { key = "${OPTIMISM_SCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "preserve"

[invariant]
runs = 512
depth = 128
fail_on_revert = false

